import { useState } from "react";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Sparkles, AlertTriangle, ArrowLeft } from "lucide-react";

const POLICY_TYPES = ["Terms & Conditions", "Privacy Policy", "Refund Policy"];
const BUSINESS_TYPES = [
  "Freelancer",
  "Agency",
  "E-commerce",
  "Clinic",
  "SaaS",
  "Consultant",
  "Restaurant",
  "Other",
];

export default function NewPolicy() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({
    business_name: "",
    business_type: "",
    country: "",
    policy_type: "",
    services_offered: "",
    payment_methods: "",
    refund_rules: "",
    data_collection: "",
    special_requirements: "",
  });

  const update = (k: string, v: string) => setForm((f) => ({ ...f, [k]: v }));

  const handleGenerate = async () => {
    if (!form.business_name || !form.business_type || !form.country || !form.policy_type) {
      toast.error("Please fill in business name, type, country and policy type.");
      return;
    }
    setLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-policy", { body: form });
      if (error) throw error;
      const content = (data as { content?: string })?.content;
      if (!content) throw new Error("No content returned");

      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;
      if (!userId) throw new Error("Not authenticated");

      const { data: inserted, error: insertErr } = await supabase
        .from("policies")
        .insert({ ...form, content, user_id: userId })
        .select("id")
        .single();
      if (insertErr) throw insertErr;

      toast.success("Policy generated");
      navigate(`/dashboard/policies/${inserted.id}`);
    } catch (e: any) {
      toast.error(e?.message ?? "Failed to generate policy");
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout>
      <Button variant="ghost" size="sm" onClick={() => navigate("/dashboard/policies")} className="mb-4">
        <ArrowLeft className="w-4 h-4 mr-2" /> Back to policies
      </Button>

      <h1 className="text-3xl font-semibold tracking-tight mb-2">Generate New Policy</h1>
      <p className="text-muted-foreground mb-6">
        AI will draft a professional policy tailored to your business.
      </p>

      <Alert className="mb-6 border-amber-500/40 bg-amber-500/5">
        <AlertTriangle className="h-4 w-4 text-amber-600" />
        <AlertDescription className="text-sm">
          This policy will be generated by AI and may not fully comply with all legal requirements.
          Please review with a qualified legal professional before using.
        </AlertDescription>
      </Alert>

      <div className="grid gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Business Info</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4 md:grid-cols-2">
            <div className="space-y-2">
              <Label>Business Name *</Label>
              <Input
                value={form.business_name}
                onChange={(e) => update("business_name", e.target.value)}
                placeholder="Acme Studio"
                maxLength={120}
              />
            </div>
            <div className="space-y-2">
              <Label>Business Type *</Label>
              <Select value={form.business_type} onValueChange={(v) => update("business_type", v)}>
                <SelectTrigger><SelectValue placeholder="Select type" /></SelectTrigger>
                <SelectContent>
                  {BUSINESS_TYPES.map((t) => (
                    <SelectItem key={t} value={t}>{t}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Country *</Label>
              <Input
                value={form.country}
                onChange={(e) => update("country", e.target.value)}
                placeholder="United Kingdom"
                maxLength={80}
              />
            </div>
            <div className="space-y-2">
              <Label>Policy Type *</Label>
              <Select value={form.policy_type} onValueChange={(v) => update("policy_type", v)}>
                <SelectTrigger><SelectValue placeholder="Select policy" /></SelectTrigger>
                <SelectContent>
                  {POLICY_TYPES.map((t) => (
                    <SelectItem key={t} value={t}>{t}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Additional Details</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="space-y-2">
              <Label>Services Offered</Label>
              <Textarea
                value={form.services_offered}
                onChange={(e) => update("services_offered", e.target.value)}
                placeholder="Branding, web design, ongoing support…"
                maxLength={2000}
              />
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label>Payment Methods</Label>
                <Input
                  value={form.payment_methods}
                  onChange={(e) => update("payment_methods", e.target.value)}
                  placeholder="Stripe, bank transfer"
                  maxLength={200}
                />
              </div>
              <div className="space-y-2">
                <Label>Refund Rules</Label>
                <Input
                  value={form.refund_rules}
                  onChange={(e) => update("refund_rules", e.target.value)}
                  placeholder="14-day refund window"
                  maxLength={200}
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label>Data Collected</Label>
              <Textarea
                value={form.data_collection}
                onChange={(e) => update("data_collection", e.target.value)}
                placeholder="Name, email, payment info, analytics cookies…"
                maxLength={1000}
              />
            </div>
            <div className="space-y-2">
              <Label>Special Requirements</Label>
              <Textarea
                value={form.special_requirements}
                onChange={(e) => update("special_requirements", e.target.value)}
                placeholder="Anything unique we should include…"
                maxLength={1000}
              />
            </div>
          </CardContent>
        </Card>

        <div className="flex justify-end">
          <Button onClick={handleGenerate} disabled={loading} size="lg">
            <Sparkles className="w-4 h-4 mr-2" />
            {loading ? "Generating…" : "Generate Policy"}
          </Button>
        </div>
      </div>
    </DashboardLayout>
  );
}
