// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/helpers.ts
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function requireUser(ctx) {
  if (!ctx.isAuthenticated()) return null;
  return ctx.getUserId() ?? null;
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List the signed-in user's clients and leads, newest first. Optionally filter by status or search by name, company or email.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Match against name, company or email."),
    status: z.string().trim().min(1).optional().describe("Filter by client status, e.g. lead or client."),
    limit: z.number().int().min(1).max(100).default(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!requireUser(ctx)) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, name, company, email, phone, status, service_requested, budget, timeline, lead_quality, lead_score, project_stage, created_at").is("deleted_at", null).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`name.ilike.%${search}%,company.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, clients: data ?? [] });
  }
});

// src/lib/mcp/tools/create-client.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_client_default = defineTool2({
  name: "create_client",
  title: "Create client",
  description: "Create a new client or lead record for the signed-in user.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Contact name."),
    email: z2.string().trim().email().optional(),
    company: z2.string().trim().min(1).optional(),
    phone: z2.string().trim().min(1).optional(),
    service_requested: z2.string().trim().min(1).optional(),
    project_description: z2.string().trim().min(1).optional(),
    budget: z2.string().trim().min(1).optional(),
    timeline: z2.string().trim().min(1).optional(),
    status: z2.string().trim().min(1).optional().describe("Defaults to the table default when omitted.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const userId = requireUser(ctx);
    if (!userId) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("clients").insert({ ...input, user_id: userId }).select("id, name, company, email, status, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ client: data });
  }
});

// src/lib/mcp/tools/list-proposals.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_proposals_default = defineTool3({
  name: "list_proposals",
  title: "List proposals",
  description: "List the signed-in user's proposals, newest first. Optionally filter by status (draft, sent, viewed, accepted, rejected).",
  inputSchema: {
    status: z3.string().trim().min(1).optional(),
    limit: z3.number().int().min(1).max(100).default(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!requireUser(ctx)) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("proposals").select("id, client_name, company_name, service_type, status, amount_cents, currency, client_paid, sent_at, viewed_at, accepted_at, created_at").is("deleted_at", null).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, proposals: data ?? [] });
  }
});

// src/lib/mcp/tools/get-proposal.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_proposal_default = defineTool4({
  name: "get_proposal",
  title: "Get proposal",
  description: "Fetch one of the signed-in user's proposals in full, including its written content and pricing breakdown.",
  inputSchema: { proposal_id: z4.string().uuid().describe("The proposal id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ proposal_id }, ctx) => {
    if (!requireUser(ctx)) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("proposals").select("id, client_name, company_name, service_type, project_scope, goals, deliverables, budget, timeline, notes, proposal_content, pricing_breakdown, payment_terms, tax_rate, status, amount_cents, currency, client_paid, sent_at, viewed_at, accepted_at, rejected_at, created_at, updated_at").eq("id", proposal_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("No proposal found with that id for this account.");
    return jsonResult({ proposal: data });
  }
});

// src/lib/mcp/tools/list-contracts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contracts_default = defineTool5({
  name: "list_contracts",
  title: "List contracts",
  description: "List the signed-in user's contracts, newest first. Optionally filter by status (draft, sent, viewed, signed, executed).",
  inputSchema: {
    status: z5.string().trim().min(1).optional(),
    limit: z5.number().int().min(1).max(100).default(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!requireUser(ctx)) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contracts").select("id, title, contract_type, client_name, client_email, company_name, status, amount_cents, currency, sent_at, viewed_at, signed_at, countersigned_at, created_at").is("deleted_at", null).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, contracts: data ?? [] });
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_leads_default = defineTool6({
  name: "list_leads",
  title: "List inbound leads",
  description: "List inbound leads captured by the signed-in user's lead forms and inbox, newest first, with AI qualification scores when available.",
  inputSchema: {
    status: z6.string().trim().min(1).optional(),
    limit: z6.number().int().min(1).max(100).default(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!requireUser(ctx)) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select("id, name, email, company, phone, source, status, service_requested, budget, timeline, lead_quality, lead_score, lead_score_reason, fit_score, ai_recommendation, client_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, leads: data ?? [] });
  }
});

// src/lib/mcp/tools/pipeline-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
var pipeline_summary_default = defineTool7({
  name: "pipeline_summary",
  title: "Pipeline summary",
  description: "Summarise the signed-in user's pipeline: proposal counts by status, accepted and paid value, contracts awaiting signature or countersignature, and onboarding forms still outstanding.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!requireUser(ctx)) return errorResult("Not authenticated.");
    const supabase = supabaseForUser(ctx);
    const [proposals, contracts, onboarding] = await Promise.all([
      supabase.from("proposals").select("status, amount_cents, currency, client_paid").is("deleted_at", null),
      supabase.from("contracts").select("status").is("deleted_at", null),
      supabase.from("onboarding_forms").select("status, completed_at, reviewed_at").is("deleted_at", null)
    ]);
    const firstError = proposals.error ?? contracts.error ?? onboarding.error;
    if (firstError) return errorResult(firstError.message);
    const byStatus = (rows) => (rows ?? []).reduce((acc, row) => {
      const key = row.status ?? "unknown";
      acc[key] = (acc[key] ?? 0) + 1;
      return acc;
    }, {});
    const proposalRows = proposals.data ?? [];
    const acceptedValueCents = proposalRows.filter((p) => p.status === "accepted").reduce((sum, p) => sum + (p.amount_cents ?? 0), 0);
    const paidValueCents = proposalRows.filter((p) => p.client_paid).reduce((sum, p) => sum + (p.amount_cents ?? 0), 0);
    const onboardingRows = onboarding.data ?? [];
    return jsonResult({
      proposals: {
        total: proposalRows.length,
        by_status: byStatus(proposalRows),
        accepted_value_cents: acceptedValueCents,
        paid_value_cents: paidValueCents,
        currency: proposalRows.find((p) => p.currency)?.currency ?? null
      },
      contracts: {
        total: contracts.data?.length ?? 0,
        by_status: byStatus(contracts.data)
      },
      onboarding: {
        total: onboardingRows.length,
        awaiting_client: onboardingRows.filter((f) => !f.completed_at).length,
        awaiting_review: onboardingRows.filter((f) => f.completed_at && !f.reviewed_at).length
      }
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "avtogztwdoemxuffnwyv";
var mcp_default = defineMcp({
  name: "closesync-ai",
  title: "CloseSync AI",
  version: "0.1.0",
  instructions: "Tools for CloseSync AI, a proposal, contract and client pipeline app. Every tool acts as the signed-in CloseSync user and only ever sees that user's own data. Use `pipeline_summary` for an overview, `list_clients` / `list_leads` for people, `list_proposals` and `get_proposal` for proposal detail, `list_contracts` for signature status, and `create_client` to add a new client or lead.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    pipeline_summary_default,
    list_clients_default,
    create_client_default,
    list_proposals_default,
    get_proposal_default,
    list_contracts_default,
    list_leads_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
