// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { publicClientConfig } from '@/config/public-client-config';
import type { Database } from './types';

const SUPABASE_URL = publicClientConfig.supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = publicClientConfig.supabasePublishableKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});